
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class ReadOnlyAdminWidget
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Image image52;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Image status_image;
		
		private global::Gtk.Entry dn_entry;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label labelpwd;
		
		private global::Gtk.Entry pwd_entry;
		
		private global::Gtk.Entry pwd_entry2;
		
		private global::Gtk.Label GtkLabel1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.Label msg_label;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.ReadOnlyAdminWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.ReadOnlyAdminWidget";
			// Container child llum.ReadOnlyAdminWidget.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(6));
			this.GtkAlignment.TopPadding = ((uint)(6));
			this.GtkAlignment.RightPadding = ((uint)(6));
			this.GtkAlignment.BottomPadding = ((uint)(6));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.image52 = new global::Gtk.Image ();
			this.image52.Name = "image52";
			this.image52.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "actor", global::Gtk.IconSize.Dialog);
			this.hbox4.Add (this.image52);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.image52]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Ldap Read-Only administrator");
			this.hbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox5.Add (this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Some services might need LDAP access to users passwords. This LDAP user could be useful to configure them.");
			this.label5.Wrap = true;
			this.vbox5.Add (this.label5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label5]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.status_image = new global::Gtk.Image ();
			this.status_image.TooltipMarkup = "User unavailable";
			this.status_image.Name = "status_image";
			this.status_image.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "user-busy", global::Gtk.IconSize.Menu);
			this.hbox2.Add (this.status_image);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.status_image]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.dn_entry = new global::Gtk.Entry ();
			this.dn_entry.CanFocus = true;
			this.dn_entry.Name = "dn_entry";
			this.dn_entry.Text = global::Mono.Unix.Catalog.GetString ("cn=roadmin,%%LDAP_BASE_DN%%");
			this.dn_entry.IsEditable = false;
			this.dn_entry.InvisibleChar = '•';
			this.hbox2.Add (this.dn_entry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.dn_entry]));
			w6.Position = 1;
			this.vbox5.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox5.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hseparator1]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
			this.frame2.BorderWidth = ((uint)(5));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			this.GtkAlignment2.TopPadding = ((uint)(5));
			this.GtkAlignment2.RightPadding = ((uint)(5));
			this.GtkAlignment2.BottomPadding = ((uint)(5));
			this.GtkAlignment2.BorderWidth = ((uint)(5));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelpwd = new global::Gtk.Label ();
			this.labelpwd.Name = "labelpwd";
			this.labelpwd.Xalign = 0F;
			this.labelpwd.LabelProp = global::Mono.Unix.Catalog.GetString ("Password (again)");
			this.table1.Add (this.labelpwd);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelpwd]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.pwd_entry = new global::Gtk.Entry ();
			this.pwd_entry.CanFocus = true;
			this.pwd_entry.Name = "pwd_entry";
			this.pwd_entry.IsEditable = true;
			this.pwd_entry.Visibility = false;
			this.pwd_entry.InvisibleChar = '•';
			this.table1.Add (this.pwd_entry);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.pwd_entry]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.pwd_entry2 = new global::Gtk.Entry ();
			this.pwd_entry2.CanFocus = true;
			this.pwd_entry2.Name = "pwd_entry2";
			this.pwd_entry2.IsEditable = true;
			this.pwd_entry2.Visibility = false;
			this.pwd_entry2.InvisibleChar = '•';
			this.table1.Add (this.pwd_entry2);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.pwd_entry2]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.table1);
			this.frame2.Add (this.GtkAlignment2);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.Xpad = 5;
			this.GtkLabel1.Ypad = 2;
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Change password</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel1;
			this.vbox5.Add (this.frame2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame2]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseStock = true;
			this.button1.UseUnderline = true;
			this.button1.Label = "gtk-apply";
			this.hbox1.Add (this.button1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox5.Add (this.hbox1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox1]));
			w17.Position = 5;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.msg_label = new global::Gtk.Label ();
			this.msg_label.Name = "msg_label";
			this.vbox5.Add (this.msg_label);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.msg_label]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 6;
			w18.Expand = false;
			w18.Fill = false;
			this.GtkAlignment.Add (this.vbox5);
			this.frame1.Add (this.GtkAlignment);
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		}
	}
}
