
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class DeleteGroupsWidget
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Image image52;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView groupListTreeview;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.CheckButton deleteUsersCheckbutton;
		
		private global::Gtk.CheckButton delete_checkbutton;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView userListTreeview;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Button acceptButton;
		
		private global::Gtk.Button cancelButton;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.Label msgLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.DeleteGroupsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.DeleteGroupsWidget";
			// Container child llum.DeleteGroupsWidget.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(6));
			this.GtkAlignment.TopPadding = ((uint)(6));
			this.GtkAlignment.RightPadding = ((uint)(6));
			this.GtkAlignment.BottomPadding = ((uint)(6));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.image52 = new global::Gtk.Image ();
			this.image52.Name = "image52";
			this.image52.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "dialog-cancel", global::Gtk.IconSize.Dialog);
			this.hbox4.Add (this.image52);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.image52]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Delete Groups");
			this.hbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox5.Add (this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("The follwing users are going to be deleted:");
			this.vbox5.Add (this.label5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label5]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.groupListTreeview = new global::Gtk.TreeView ();
			this.groupListTreeview.Name = "groupListTreeview";
			this.GtkScrolledWindow.Add (this.groupListTreeview);
			this.vbox5.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow]));
			w6.Position = 2;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.deleteUsersCheckbutton = new global::Gtk.CheckButton ();
			this.deleteUsersCheckbutton.CanFocus = true;
			this.deleteUsersCheckbutton.Name = "deleteUsersCheckbutton";
			this.deleteUsersCheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Delete users belonging to those groups");
			this.deleteUsersCheckbutton.DrawIndicator = true;
			this.deleteUsersCheckbutton.UseUnderline = true;
			this.hbox1.Add (this.deleteUsersCheckbutton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.deleteUsersCheckbutton]));
			w7.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.delete_checkbutton = new global::Gtk.CheckButton ();
			this.delete_checkbutton.Sensitive = false;
			this.delete_checkbutton.CanFocus = true;
			this.delete_checkbutton.Name = "delete_checkbutton";
			this.delete_checkbutton.Label = global::Mono.Unix.Catalog.GetString ("Delete /net user data as well");
			this.delete_checkbutton.Active = true;
			this.delete_checkbutton.DrawIndicator = true;
			this.delete_checkbutton.UseUnderline = true;
			this.hbox1.Add (this.delete_checkbutton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.delete_checkbutton]));
			w8.Position = 1;
			this.vbox5.Add (this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox1]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.userListTreeview = new global::Gtk.TreeView ();
			this.userListTreeview.Sensitive = false;
			this.userListTreeview.CanFocus = true;
			this.userListTreeview.Name = "userListTreeview";
			this.GtkScrolledWindow1.Add (this.userListTreeview);
			this.vbox5.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow1]));
			w11.Position = 4;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.acceptButton = new global::Gtk.Button ();
			this.acceptButton.CanFocus = true;
			this.acceptButton.Name = "acceptButton";
			this.acceptButton.UseStock = true;
			this.acceptButton.UseUnderline = true;
			this.acceptButton.Label = "gtk-apply";
			this.hbox5.Add (this.acceptButton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.acceptButton]));
			w12.Position = 0;
			w12.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.cancelButton = new global::Gtk.Button ();
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseStock = true;
			this.cancelButton.UseUnderline = true;
			this.cancelButton.Label = "gtk-cancel";
			this.hbox5.Add (this.cancelButton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.cancelButton]));
			w13.Position = 1;
			w13.Fill = false;
			this.vbox5.Add (this.hbox5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox5]));
			w14.Position = 5;
			w14.Expand = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w15 = new global::Gtk.Viewport ();
			w15.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.msgLabel = new global::Gtk.Label ();
			this.msgLabel.Name = "msgLabel";
			w15.Add (this.msgLabel);
			this.GtkScrolledWindow2.Add (w15);
			this.vbox5.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow2]));
			w18.Position = 6;
			this.GtkAlignment.Add (this.vbox5);
			this.frame1.Add (this.GtkAlignment);
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.deleteUsersCheckbutton.Toggled += new global::System.EventHandler (this.OnDeleteUsersCheckbuttonToggled);
			this.acceptButton.Clicked += new global::System.EventHandler (this.OnAcceptButtonClicked);
			this.cancelButton.Clicked += new global::System.EventHandler (this.OnCancelButtonClicked);
		}
	}
}
