
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class ImportExportWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Image image1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.FileChooserButton exportFilechooserbutton;
		
		private global::Gtk.Button exportButton;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.FileChooserButton importFilechooserbutton;
		
		private global::Gtk.Button importButton;
		
		private global::Gtk.CheckButton regenerateCb;
		
		private global::Gtk.Label msg_label;
		
		private global::Gtk.HSeparator hseparator3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.ImportExportWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.ImportExportWidget";
			// Container child llum.ImportExportWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 12;
			this.vbox1.BorderWidth = ((uint)(7));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-floppy", global::Gtk.IconSize.Dialog);
			this.hbox3.Add (this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Import/Export operations");
			this.label2.UseMarkup = true;
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("This option allows you to export users and groups to a json file and import them to other initialized servers");
			this.label3.Wrap = true;
			this.vbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Export to file:</b>");
			this.label4.UseMarkup = true;
			this.vbox1.Add (this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label4]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.exportFilechooserbutton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select destination folder"), ((global::Gtk.FileChooserAction)(2)));
			this.exportFilechooserbutton.Name = "exportFilechooserbutton";
			this.hbox1.Add (this.exportFilechooserbutton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.exportFilechooserbutton]));
			w7.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.exportButton = new global::Gtk.Button ();
			this.exportButton.CanFocus = true;
			this.exportButton.Name = "exportButton";
			this.exportButton.UseUnderline = true;
			this.exportButton.Label = global::Mono.Unix.Catalog.GetString ("Export");
			this.hbox1.Add (this.exportButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.exportButton]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w9.Position = 4;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator2]));
			w10.Position = 5;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Import from file:</b>");
			this.label5.UseMarkup = true;
			this.vbox1.Add (this.label5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label5]));
			w11.Position = 6;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.importFilechooserbutton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Seleccionar un archivo"), ((global::Gtk.FileChooserAction)(0)));
			this.importFilechooserbutton.Name = "importFilechooserbutton";
			this.hbox2.Add (this.importFilechooserbutton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.importFilechooserbutton]));
			w12.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.importButton = new global::Gtk.Button ();
			this.importButton.CanFocus = true;
			this.importButton.Name = "importButton";
			this.importButton.UseUnderline = true;
			this.importButton.Label = global::Mono.Unix.Catalog.GetString ("Import");
			this.hbox2.Add (this.importButton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.importButton]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w14.Position = 7;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.regenerateCb = new global::Gtk.CheckButton ();
			this.regenerateCb.CanFocus = true;
			this.regenerateCb.Name = "regenerateCb";
			this.regenerateCb.Label = global::Mono.Unix.Catalog.GetString ("Regenerate random passwords for every user (students AND teachers)");
			this.regenerateCb.DrawIndicator = true;
			this.regenerateCb.UseUnderline = true;
			this.vbox1.Add (this.regenerateCb);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.regenerateCb]));
			w15.Position = 8;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.msg_label = new global::Gtk.Label ();
			this.msg_label.Name = "msg_label";
			this.vbox1.Add (this.msg_label);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.msg_label]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 9;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox1.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator3]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 10;
			w17.Expand = false;
			w17.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.exportButton.Clicked += new global::System.EventHandler (this.OnExportButtonClicked);
			this.importButton.Clicked += new global::System.EventHandler (this.OnImportButtonClicked);
		}
	}
}
