
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class EditGroupWidget
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image image230;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label gidNumberLabel;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label gidLabel;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry descriptionEntry;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Button undoButton;
		
		private global::Gtk.Button applyDescriptionButton;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView otherUsersTreeview;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Button addUserbutton;
		
		private global::Gtk.Image image246;
		
		private global::Gtk.Button deleteUserbutton;
		
		private global::Gtk.Image image245;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView usersInGroupTreeview;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Entry passwordEntry;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Entry passwordEntry2;
		
		private global::Gtk.VSeparator vseparator2;
		
		private global::Gtk.Button applyPasswordButton;
		
		private global::Gtk.Label GtkLabel4;
		
		private global::Gtk.Label msgLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.EditGroupWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.EditGroupWidget";
			// Container child llum.EditGroupWidget.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(6));
			this.GtkAlignment.TopPadding = ((uint)(6));
			this.GtkAlignment.RightPadding = ((uint)(6));
			this.GtkAlignment.BottomPadding = ((uint)(6));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image230 = new global::Gtk.Image ();
			this.image230.Name = "image230";
			this.image230.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "folder-public", global::Gtk.IconSize.Dialog);
			this.hbox1.Add (this.image230);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image230]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Group Details");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 150;
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Group GID#</b>");
			this.label2.UseMarkup = true;
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.gidNumberLabel = new global::Gtk.Label ();
			this.gidNumberLabel.Name = "gidNumberLabel";
			this.gidNumberLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.hbox2.Add (this.gidNumberLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.gidNumberLabel]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 150;
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Group GID</b>");
			this.label4.UseMarkup = true;
			this.hbox3.Add (this.label4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label4]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.gidLabel = new global::Gtk.Label ();
			this.gidLabel.Name = "gidLabel";
			this.gidLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label5");
			this.hbox3.Add (this.gidLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.gidLabel]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(7));
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(6));
			this.GtkAlignment1.TopPadding = ((uint)(6));
			this.GtkAlignment1.RightPadding = ((uint)(6));
			this.GtkAlignment1.BottomPadding = ((uint)(6));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Description");
			this.hbox4.Add (this.label6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label6]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.descriptionEntry = new global::Gtk.Entry ();
			this.descriptionEntry.CanFocus = true;
			this.descriptionEntry.Name = "descriptionEntry";
			this.descriptionEntry.IsEditable = true;
			this.descriptionEntry.InvisibleChar = '●';
			this.hbox4.Add (this.descriptionEntry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.descriptionEntry]));
			w12.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox4.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vseparator1]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.undoButton = new global::Gtk.Button ();
			this.undoButton.CanFocus = true;
			this.undoButton.Name = "undoButton";
			this.undoButton.UseStock = true;
			this.undoButton.UseUnderline = true;
			this.undoButton.Label = "gtk-undo";
			this.vbox2.Add (this.undoButton);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.undoButton]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.applyDescriptionButton = new global::Gtk.Button ();
			this.applyDescriptionButton.CanFocus = true;
			this.applyDescriptionButton.Name = "applyDescriptionButton";
			this.applyDescriptionButton.UseStock = true;
			this.applyDescriptionButton.UseUnderline = true;
			this.applyDescriptionButton.Label = "gtk-apply";
			this.vbox2.Add (this.applyDescriptionButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.applyDescriptionButton]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox4.Add (this.vbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox2]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			this.GtkAlignment1.Add (this.hbox4);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.Xpad = 6;
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Edit Description</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel2;
			this.vbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(6));
			this.GtkAlignment4.TopPadding = ((uint)(6));
			this.GtkAlignment4.RightPadding = ((uint)(6));
			this.GtkAlignment4.BottomPadding = ((uint)(6));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.otherUsersTreeview = new global::Gtk.TreeView ();
			this.otherUsersTreeview.CanFocus = true;
			this.otherUsersTreeview.Name = "otherUsersTreeview";
			this.GtkScrolledWindow1.Add (this.otherUsersTreeview);
			this.hbox6.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.GtkScrolledWindow1]));
			w21.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.addUserbutton = new global::Gtk.Button ();
			this.addUserbutton.CanFocus = true;
			this.addUserbutton.Name = "addUserbutton";
			// Container child addUserbutton.Gtk.Container+ContainerChild
			this.image246 = new global::Gtk.Image ();
			this.image246.Name = "image246";
			this.image246.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.addUserbutton.Add (this.image246);
			this.vbox4.Add (this.addUserbutton);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.addUserbutton]));
			w23.Position = 0;
			w23.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.deleteUserbutton = new global::Gtk.Button ();
			this.deleteUserbutton.CanFocus = true;
			this.deleteUserbutton.Name = "deleteUserbutton";
			// Container child deleteUserbutton.Gtk.Container+ContainerChild
			this.image245 = new global::Gtk.Image ();
			this.image245.Name = "image245";
			this.image245.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			this.deleteUserbutton.Add (this.image245);
			this.vbox4.Add (this.deleteUserbutton);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.deleteUserbutton]));
			w25.PackType = ((global::Gtk.PackType)(1));
			w25.Position = 1;
			w25.Fill = false;
			this.hbox6.Add (this.vbox4);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox4]));
			w26.Position = 1;
			w26.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.usersInGroupTreeview = new global::Gtk.TreeView ();
			this.usersInGroupTreeview.CanFocus = true;
			this.usersInGroupTreeview.Name = "usersInGroupTreeview";
			this.GtkScrolledWindow.Add (this.usersInGroupTreeview);
			this.hbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.GtkScrolledWindow]));
			w28.Position = 2;
			this.vbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
			w29.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Change password to every user in this group:</b>");
			this.label9.UseMarkup = true;
			this.vbox3.Add (this.label9);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label9]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.WidthRequest = 150;
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter password:");
			this.hbox8.Add (this.label10);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label10]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.passwordEntry = new global::Gtk.Entry ();
			this.passwordEntry.CanFocus = true;
			this.passwordEntry.Name = "passwordEntry";
			this.passwordEntry.IsEditable = true;
			this.passwordEntry.Visibility = false;
			this.passwordEntry.InvisibleChar = '●';
			this.hbox8.Add (this.passwordEntry);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.passwordEntry]));
			w32.Position = 1;
			this.vbox5.Add (this.hbox8);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox8]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.WidthRequest = 150;
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Re-enter password:");
			this.hbox9.Add (this.label11);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label11]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.passwordEntry2 = new global::Gtk.Entry ();
			this.passwordEntry2.CanFocus = true;
			this.passwordEntry2.Name = "passwordEntry2";
			this.passwordEntry2.IsEditable = true;
			this.passwordEntry2.Visibility = false;
			this.passwordEntry2.InvisibleChar = '●';
			this.hbox9.Add (this.passwordEntry2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.passwordEntry2]));
			w35.Position = 1;
			this.vbox5.Add (this.hbox9);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox9]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.hbox7.Add (this.vbox5);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox5]));
			w37.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hbox7.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator2]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.applyPasswordButton = new global::Gtk.Button ();
			this.applyPasswordButton.CanFocus = true;
			this.applyPasswordButton.Name = "applyPasswordButton";
			this.applyPasswordButton.UseStock = true;
			this.applyPasswordButton.UseUnderline = true;
			this.applyPasswordButton.Label = "gtk-apply";
			this.hbox7.Add (this.applyPasswordButton);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.applyPasswordButton]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox3.Add (this.hbox7);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox7]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.GtkAlignment4.Add (this.vbox3);
			this.frame3.Add (this.GtkAlignment4);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.Xpad = 6;
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Edit Users</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel4;
			this.vbox1.Add (this.frame3);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame3]));
			w43.Position = 5;
			// Container child vbox1.Gtk.Box+BoxChild
			this.msgLabel = new global::Gtk.Label ();
			this.msgLabel.Name = "msgLabel";
			this.vbox1.Add (this.msgLabel);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.msgLabel]));
			w44.Position = 6;
			w44.Expand = false;
			w44.Fill = false;
			this.GtkAlignment.Add (this.vbox1);
			this.frame1.Add (this.GtkAlignment);
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.undoButton.Clicked += new global::System.EventHandler (this.OnUndoButtonClicked);
			this.applyDescriptionButton.Clicked += new global::System.EventHandler (this.OnApplyDescriptionButtonClicked);
			this.addUserbutton.Clicked += new global::System.EventHandler (this.OnAddUserButtonClicked);
			this.deleteUserbutton.Clicked += new global::System.EventHandler (this.OnDeleteUserButtonClicked);
			this.passwordEntry.Changed += new global::System.EventHandler (this.OnPasswordEntryChanged);
			this.passwordEntry2.Changed += new global::System.EventHandler (this.OnPasswordEntry2Changed);
			this.applyPasswordButton.Clicked += new global::System.EventHandler (this.OnApplyPasswordButtonClicked);
		}
	}
}
