
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class GescenImportWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image image11;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.HBox fileHbox;
		
		private global::Gtk.FileChooserButton gescenFilechooserbutton;
		
		private global::Gtk.Button sendGescenButton;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.CheckButton apply_passwd_checkbutton;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label passwd_label;
		
		private global::Gtk.Entry itaca_passwd_entry;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.HBox groupHbox;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView groupListTreeview;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.RadioButton partialRadiobutton;
		
		private global::Gtk.Button clearButton;
		
		private global::Gtk.RadioButton completeRadiobutton;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Button importButton;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HBox usersToDeleteHbox;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView usersToDeleteTreeview;
		
		private global::Gtk.VSeparator vseparator2;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Button deleteButton;
		
		private global::Gtk.Button cancelDeleteButton;
		
		private global::Gtk.Label msgLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.GescenImportWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.GescenImportWidget";
			// Container child llum.GescenImportWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image11 = new global::Gtk.Image ();
			this.image11.Name = "image11";
			this.image11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "document-new", global::Gtk.IconSize.Dialog);
			this.hbox1.Add (this.image11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Gescen Importation");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Select GESCEN/ITACA file:");
			this.vbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fileHbox = new global::Gtk.HBox ();
			this.fileHbox.Name = "fileHbox";
			this.fileHbox.Spacing = 6;
			// Container child fileHbox.Gtk.Box+BoxChild
			this.gescenFilechooserbutton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a file"), ((global::Gtk.FileChooserAction)(0)));
			this.gescenFilechooserbutton.Name = "gescenFilechooserbutton";
			this.fileHbox.Add (this.gescenFilechooserbutton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.fileHbox [this.gescenFilechooserbutton]));
			w5.Position = 0;
			// Container child fileHbox.Gtk.Box+BoxChild
			this.sendGescenButton = new global::Gtk.Button ();
			this.sendGescenButton.CanFocus = true;
			this.sendGescenButton.Name = "sendGescenButton";
			this.sendGescenButton.UseStock = true;
			this.sendGescenButton.UseUnderline = true;
			this.sendGescenButton.Label = "gtk-apply";
			this.fileHbox.Add (this.sendGescenButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.fileHbox [this.sendGescenButton]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox1.Add (this.fileHbox);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fileHbox]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.apply_passwd_checkbutton = new global::Gtk.CheckButton ();
			this.apply_passwd_checkbutton.CanFocus = true;
			this.apply_passwd_checkbutton.Name = "apply_passwd_checkbutton";
			this.apply_passwd_checkbutton.Label = global::Mono.Unix.Catalog.GetString ("Apply password to ITACA file");
			this.apply_passwd_checkbutton.DrawIndicator = true;
			this.apply_passwd_checkbutton.UseUnderline = true;
			this.hbox7.Add (this.apply_passwd_checkbutton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.apply_passwd_checkbutton]));
			w8.Position = 0;
			this.vbox1.Add (this.hbox7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.passwd_label = new global::Gtk.Label ();
			this.passwd_label.Sensitive = false;
			this.passwd_label.Name = "passwd_label";
			this.passwd_label.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.hbox6.Add (this.passwd_label);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.passwd_label]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.itaca_passwd_entry = new global::Gtk.Entry ();
			this.itaca_passwd_entry.Sensitive = false;
			this.itaca_passwd_entry.CanFocus = true;
			this.itaca_passwd_entry.Name = "itaca_passwd_entry";
			this.itaca_passwd_entry.IsEditable = true;
			this.itaca_passwd_entry.InvisibleChar = '•';
			this.hbox6.Add (this.itaca_passwd_entry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.itaca_passwd_entry]));
			w11.Position = 1;
			w11.Expand = false;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator2]));
			w13.Position = 5;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.groupHbox = new global::Gtk.HBox ();
			this.groupHbox.Name = "groupHbox";
			this.groupHbox.Spacing = 6;
			// Container child groupHbox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.groupListTreeview = new global::Gtk.TreeView ();
			this.groupListTreeview.CanFocus = true;
			this.groupListTreeview.Name = "groupListTreeview";
			this.GtkScrolledWindow.Add (this.groupListTreeview);
			this.groupHbox.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.groupHbox [this.GtkScrolledWindow]));
			w15.Position = 0;
			// Container child groupHbox.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.groupHbox.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.groupHbox [this.vseparator1]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child groupHbox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Importation Mode:");
			this.vbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label3]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.partialRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Partial"));
			this.partialRadiobutton.CanFocus = true;
			this.partialRadiobutton.Name = "partialRadiobutton";
			this.partialRadiobutton.DrawIndicator = true;
			this.partialRadiobutton.UseUnderline = true;
			this.partialRadiobutton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox2.Add (this.partialRadiobutton);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.partialRadiobutton]));
			w18.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.clearButton = new global::Gtk.Button ();
			this.clearButton.CanFocus = true;
			this.clearButton.Name = "clearButton";
			this.clearButton.UseUnderline = true;
			this.clearButton.Label = global::Mono.Unix.Catalog.GetString ("Clear selection");
			global::Gtk.Image w19 = new global::Gtk.Image ();
			w19.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.clearButton.Image = w19;
			this.hbox2.Add (this.clearButton);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.clearButton]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.completeRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Complete"));
			this.completeRadiobutton.CanFocus = true;
			this.completeRadiobutton.Name = "completeRadiobutton";
			this.completeRadiobutton.DrawIndicator = true;
			this.completeRadiobutton.UseUnderline = true;
			this.completeRadiobutton.Group = this.partialRadiobutton.Group;
			this.vbox2.Add (this.completeRadiobutton);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.completeRadiobutton]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.importButton = new global::Gtk.Button ();
			this.importButton.CanFocus = true;
			this.importButton.Name = "importButton";
			this.importButton.UseStock = true;
			this.importButton.UseUnderline = true;
			this.importButton.Label = "gtk-ok";
			this.hbox3.Add (this.importButton);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.importButton]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w24.Position = 3;
			w24.Expand = false;
			w24.Fill = false;
			this.groupHbox.Add (this.vbox2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.groupHbox [this.vbox2]));
			w25.Position = 2;
			this.vbox1.Add (this.groupHbox);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.groupHbox]));
			w26.Position = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w27.Position = 7;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.usersToDeleteHbox = new global::Gtk.HBox ();
			this.usersToDeleteHbox.Name = "usersToDeleteHbox";
			this.usersToDeleteHbox.Spacing = 6;
			// Container child usersToDeleteHbox.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.WidthRequest = 235;
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.usersToDeleteTreeview = new global::Gtk.TreeView ();
			this.usersToDeleteTreeview.CanFocus = true;
			this.usersToDeleteTreeview.Name = "usersToDeleteTreeview";
			this.GtkScrolledWindow1.Add (this.usersToDeleteTreeview);
			this.usersToDeleteHbox.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.usersToDeleteHbox [this.GtkScrolledWindow1]));
			w29.Position = 0;
			// Container child usersToDeleteHbox.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.usersToDeleteHbox.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.usersToDeleteHbox [this.vseparator2]));
			w30.Position = 1;
			w30.Expand = false;
			// Container child usersToDeleteHbox.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(6));
			// Container child vbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("This is a list of users from previous Gescen/Itaca importations that were not found in the current xml.\n<b>Do you want to delete them?</b>");
			this.label4.UseMarkup = true;
			this.label4.Wrap = true;
			this.vbox3.Add (this.label4);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label4]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.deleteButton = new global::Gtk.Button ();
			this.deleteButton.CanFocus = true;
			this.deleteButton.Name = "deleteButton";
			this.deleteButton.UseStock = true;
			this.deleteButton.UseUnderline = true;
			this.deleteButton.Label = "gtk-ok";
			this.hbox5.Add (this.deleteButton);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.deleteButton]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.cancelDeleteButton = new global::Gtk.Button ();
			this.cancelDeleteButton.CanFocus = true;
			this.cancelDeleteButton.Name = "cancelDeleteButton";
			this.cancelDeleteButton.UseStock = true;
			this.cancelDeleteButton.UseUnderline = true;
			this.cancelDeleteButton.Label = "gtk-cancel";
			this.hbox5.Add (this.cancelDeleteButton);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.cancelDeleteButton]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.hbox4.Add (this.vbox3);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
			w35.Position = 0;
			this.usersToDeleteHbox.Add (this.hbox4);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.usersToDeleteHbox [this.hbox4]));
			w36.Position = 2;
			this.vbox1.Add (this.usersToDeleteHbox);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.usersToDeleteHbox]));
			w37.Position = 8;
			// Container child vbox1.Gtk.Box+BoxChild
			this.msgLabel = new global::Gtk.Label ();
			this.msgLabel.Name = "msgLabel";
			this.vbox1.Add (this.msgLabel);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.msgLabel]));
			w38.PackType = ((global::Gtk.PackType)(1));
			w38.Position = 9;
			w38.Expand = false;
			w38.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.sendGescenButton.Clicked += new global::System.EventHandler (this.OnSendGescenButtonClicked);
			this.apply_passwd_checkbutton.Toggled += new global::System.EventHandler (this.OnCheckbutton1Toggled);
			this.groupListTreeview.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnGroupListTreeviewButtonReleaseEvent);
			this.clearButton.Clicked += new global::System.EventHandler (this.OnClearButtonClicked);
			this.completeRadiobutton.Toggled += new global::System.EventHandler (this.OnCompleteRadiobuttonToggled);
			this.importButton.Clicked += new global::System.EventHandler (this.OnImportButtonClicked);
			this.deleteButton.Clicked += new global::System.EventHandler (this.OnDeleteButtonClicked);
			this.cancelDeleteButton.Clicked += new global::System.EventHandler (this.OnCancelDeleteButtonClicked);
		}
	}
}
