
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class ChangeOwnPassword
	{
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image image1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry oldPasswordEntry;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry password1Entry;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry password2Entry;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Button acceptButton;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Label msgLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.ChangeOwnPassword
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.ChangeOwnPassword";
			// Container child llum.ChangeOwnPassword.Gtk.Container+ContainerChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame2.BorderWidth = ((uint)(5));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(6));
			this.GtkAlignment.TopPadding = ((uint)(6));
			this.GtkAlignment.RightPadding = ((uint)(6));
			this.GtkAlignment.BottomPadding = ((uint)(6));
			this.GtkAlignment.BorderWidth = ((uint)(6));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "system-lock-screen", global::Gtk.IconSize.Dialog);
			this.hbox1.Add (this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Change your password");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 300;
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter your old password:");
			this.hbox6.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.oldPasswordEntry = new global::Gtk.Entry ();
			this.oldPasswordEntry.CanFocus = true;
			this.oldPasswordEntry.Name = "oldPasswordEntry";
			this.oldPasswordEntry.IsEditable = true;
			this.oldPasswordEntry.Visibility = false;
			this.oldPasswordEntry.InvisibleChar = '●';
			this.hbox6.Add (this.oldPasswordEntry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.oldPasswordEntry]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 300;
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter your new password:");
			this.hbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.password1Entry = new global::Gtk.Entry ();
			this.password1Entry.CanFocus = true;
			this.password1Entry.Name = "password1Entry";
			this.password1Entry.IsEditable = true;
			this.password1Entry.Visibility = false;
			this.password1Entry.InvisibleChar = '●';
			this.hbox2.Add (this.password1Entry);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.password1Entry]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 300;
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Re-enter your new password:");
			this.hbox5.Add (this.label4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label4]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.password2Entry = new global::Gtk.Entry ();
			this.password2Entry.CanFocus = true;
			this.password2Entry.Name = "password2Entry";
			this.password2Entry.IsEditable = true;
			this.password2Entry.Visibility = false;
			this.password2Entry.InvisibleChar = '●';
			this.hbox5.Add (this.password2Entry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.password2Entry]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.acceptButton = new global::Gtk.Button ();
			this.acceptButton.Sensitive = false;
			this.acceptButton.CanFocus = true;
			this.acceptButton.Name = "acceptButton";
			this.acceptButton.UseStock = true;
			this.acceptButton.UseUnderline = true;
			this.acceptButton.Label = "gtk-ok";
			this.hbox3.Add (this.acceptButton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.acceptButton]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(200));
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(6));
			this.GtkAlignment2.TopPadding = ((uint)(6));
			this.GtkAlignment2.RightPadding = ((uint)(6));
			this.GtkAlignment2.BottomPadding = ((uint)(6));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.msgLabel = new global::Gtk.Label ();
			this.msgLabel.Name = "msgLabel";
			this.msgLabel.UseMarkup = true;
			this.GtkAlignment2.Add (this.msgLabel);
			this.frame1.Add (this.GtkAlignment2);
			this.vbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
			w17.Position = 5;
			w17.Expand = false;
			w17.Fill = false;
			this.GtkAlignment.Add (this.vbox1);
			this.frame2.Add (this.GtkAlignment);
			this.Add (this.frame2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.oldPasswordEntry.Changed += new global::System.EventHandler (this.OnOldPasswordEntryChanged);
			this.password1Entry.Changed += new global::System.EventHandler (this.OnPassword1EntryChanged);
			this.password2Entry.Changed += new global::System.EventHandler (this.OnPassword2EntryChanged);
			this.acceptButton.Clicked += new global::System.EventHandler (this.OnAcceptButtonClicked);
		}
	}
}
