
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class AddGenericUsersWidget
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Image image11;
		
		private global::Gtk.Image image12;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBox groupCombobox;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ComboBox templateCombobox;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.SpinButton numberSpinbutton;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label exampleLabel;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry genericNameEntry;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment5;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.RadioButton randomPasswordradiobutton;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.RadioButton sameAsUserRadiobutton;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.RadioButton setPasswordRadiobutton;
		
		private global::Gtk.Entry passwordEntry;
		
		private global::Gtk.Label GtkLabel4;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Button acceptButton;
		
		private global::Gtk.Button undoButton;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.Label msgLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.AddGenericUsersWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.AddGenericUsersWidget";
			// Container child llum.AddGenericUsersWidget.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(6));
			this.GtkAlignment.TopPadding = ((uint)(6));
			this.GtkAlignment.RightPadding = ((uint)(6));
			this.GtkAlignment.BottomPadding = ((uint)(6));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.image11 = new global::Gtk.Image ();
			this.image11.Name = "image11";
			this.image11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "actor", global::Gtk.IconSize.Dialog);
			this.hbox3.Add (this.image11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.image11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.image12 = new global::Gtk.Image ();
			this.image12.Name = "image12";
			this.image12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.hbox3.Add (this.image12);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.image12]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Add generic users");
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Add users to this group");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.groupCombobox = global::Gtk.ComboBox.NewText ();
			this.groupCombobox.Name = "groupCombobox";
			this.hbox1.Add (this.groupCombobox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.groupCombobox]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Users template");
			this.hbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.templateCombobox = global::Gtk.ComboBox.NewText ();
			this.templateCombobox.Name = "templateCombobox";
			this.hbox2.Add (this.templateCombobox);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.templateCombobox]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of users to create");
			this.hbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.numberSpinbutton = new global::Gtk.SpinButton (1, 100, 1);
			this.numberSpinbutton.CanFocus = true;
			this.numberSpinbutton.Name = "numberSpinbutton";
			this.numberSpinbutton.Adjustment.PageIncrement = 10;
			this.numberSpinbutton.ClimbRate = 1;
			this.numberSpinbutton.Numeric = true;
			this.numberSpinbutton.Value = 1;
			this.hbox4.Add (this.numberSpinbutton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.numberSpinbutton]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.exampleLabel = new global::Gtk.Label ();
			this.exampleLabel.Name = "exampleLabel";
			this.hbox5.Add (this.exampleLabel);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.exampleLabel]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Generic name");
			this.hbox5.Add (this.label5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.genericNameEntry = new global::Gtk.Entry ();
			this.genericNameEntry.Sensitive = false;
			this.genericNameEntry.CanFocus = true;
			this.genericNameEntry.Name = "genericNameEntry";
			this.genericNameEntry.IsEditable = true;
			this.genericNameEntry.InvisibleChar = '●';
			this.hbox5.Add (this.genericNameEntry);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.genericNameEntry]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox5.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vseparator1]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 3;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w19.Position = 5;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(6));
			this.GtkAlignment5.TopPadding = ((uint)(6));
			this.GtkAlignment5.RightPadding = ((uint)(6));
			this.GtkAlignment5.BottomPadding = ((uint)(6));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.randomPasswordradiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Random password"));
			this.randomPasswordradiobutton.CanFocus = true;
			this.randomPasswordradiobutton.Name = "randomPasswordradiobutton";
			this.randomPasswordradiobutton.DrawIndicator = true;
			this.randomPasswordradiobutton.UseUnderline = true;
			this.randomPasswordradiobutton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox7.Add (this.randomPasswordradiobutton);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.randomPasswordradiobutton]));
			w20.Position = 0;
			this.vbox2.Add (this.hbox7);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.sameAsUserRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Same as user name"));
			this.sameAsUserRadiobutton.CanFocus = true;
			this.sameAsUserRadiobutton.Name = "sameAsUserRadiobutton";
			this.sameAsUserRadiobutton.DrawIndicator = true;
			this.sameAsUserRadiobutton.UseUnderline = true;
			this.sameAsUserRadiobutton.Group = this.randomPasswordradiobutton.Group;
			this.hbox8.Add (this.sameAsUserRadiobutton);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.sameAsUserRadiobutton]));
			w22.Position = 0;
			this.vbox2.Add (this.hbox8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.setPasswordRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Same password for every user"));
			this.setPasswordRadiobutton.CanFocus = true;
			this.setPasswordRadiobutton.Name = "setPasswordRadiobutton";
			this.setPasswordRadiobutton.DrawIndicator = true;
			this.setPasswordRadiobutton.UseUnderline = true;
			this.setPasswordRadiobutton.Group = this.randomPasswordradiobutton.Group;
			this.hbox9.Add (this.setPasswordRadiobutton);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.setPasswordRadiobutton]));
			w24.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.passwordEntry = new global::Gtk.Entry ();
			this.passwordEntry.Sensitive = false;
			this.passwordEntry.CanFocus = true;
			this.passwordEntry.Name = "passwordEntry";
			this.passwordEntry.IsEditable = true;
			this.passwordEntry.InvisibleChar = '●';
			this.hbox9.Add (this.passwordEntry);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.passwordEntry]));
			w25.Position = 1;
			this.vbox2.Add (this.hbox9);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox9]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.GtkAlignment5.Add (this.vbox2);
			this.frame2.Add (this.GtkAlignment5);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.Xpad = 6;
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("Password generation");
			this.frame2.LabelWidget = this.GtkLabel4;
			this.vbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
			w29.Position = 6;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.acceptButton = new global::Gtk.Button ();
			this.acceptButton.CanFocus = true;
			this.acceptButton.Name = "acceptButton";
			this.acceptButton.UseStock = true;
			this.acceptButton.UseUnderline = true;
			this.acceptButton.Label = "gtk-ok";
			this.hbox6.Add (this.acceptButton);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.acceptButton]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			w30.Padding = ((uint)(60));
			// Container child hbox6.Gtk.Box+BoxChild
			this.undoButton = new global::Gtk.Button ();
			this.undoButton.CanFocus = true;
			this.undoButton.Name = "undoButton";
			this.undoButton.UseStock = true;
			this.undoButton.UseUnderline = true;
			this.undoButton.Label = "gtk-undo";
			this.hbox6.Add (this.undoButton);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.undoButton]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w32.Position = 7;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w33 = new global::Gtk.Viewport ();
			w33.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.msgLabel = new global::Gtk.Label ();
			this.msgLabel.Name = "msgLabel";
			w33.Add (this.msgLabel);
			this.GtkScrolledWindow.Add (w33);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w36.Position = 8;
			this.GtkAlignment.Add (this.vbox1);
			this.frame1.Add (this.GtkAlignment);
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.label5.Hide ();
			this.genericNameEntry.Hide ();
			this.vseparator1.Hide ();
			this.Hide ();
			this.groupCombobox.Changed += new global::System.EventHandler (this.OnGroupComboboxChanged);
			this.genericNameEntry.Changed += new global::System.EventHandler (this.OnGenericNameEntryChanged);
			this.randomPasswordradiobutton.Clicked += new global::System.EventHandler (this.OnRandomPasswordradiobuttonClicked);
			this.sameAsUserRadiobutton.Clicked += new global::System.EventHandler (this.OnSameAsUserRadiobuttonClicked);
			this.setPasswordRadiobutton.Clicked += new global::System.EventHandler (this.OnSetPasswordRadiobuttonClicked);
			this.passwordEntry.Changed += new global::System.EventHandler (this.OnPasswordEntryChanged);
			this.acceptButton.Clicked += new global::System.EventHandler (this.OnAcceptButtonClicked);
			this.undoButton.Clicked += new global::System.EventHandler (this.OnUndoButtonClicked);
		}
	}
}
