
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class ResetPasswordsWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Image image1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.RadioButton studentsRadiobutton;
		
		private global::Gtk.RadioButton teachersRadiobutton;
		
		private global::Gtk.RadioButton allRadiobutton;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.Button resetButton;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label msgLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.ResetPasswordsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.ResetPasswordsWidget";
			// Container child llum.ResetPasswordsWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "system-lock-screen", global::Gtk.IconSize.Dialog);
			this.hbox3.Add (this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Reset passwords");
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(11));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.studentsRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Students"));
			this.studentsRadiobutton.CanFocus = true;
			this.studentsRadiobutton.Name = "studentsRadiobutton";
			this.studentsRadiobutton.DrawIndicator = true;
			this.studentsRadiobutton.UseUnderline = true;
			this.studentsRadiobutton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox2.Add (this.studentsRadiobutton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.studentsRadiobutton]));
			w4.Position = 0;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.teachersRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Teachers"));
			this.teachersRadiobutton.CanFocus = true;
			this.teachersRadiobutton.Name = "teachersRadiobutton";
			this.teachersRadiobutton.DrawIndicator = true;
			this.teachersRadiobutton.UseUnderline = true;
			this.teachersRadiobutton.Group = this.studentsRadiobutton.Group;
			this.vbox2.Add (this.teachersRadiobutton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.teachersRadiobutton]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.allRadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("All users"));
			this.allRadiobutton.CanFocus = true;
			this.allRadiobutton.Name = "allRadiobutton";
			this.allRadiobutton.DrawIndicator = true;
			this.allRadiobutton.UseUnderline = true;
			this.allRadiobutton.Group = this.studentsRadiobutton.Group;
			this.vbox2.Add (this.allRadiobutton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.allRadiobutton]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w8.Position = 0;
			w8.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.resetButton = new global::Gtk.Button ();
			this.resetButton.CanFocus = true;
			this.resetButton.Name = "resetButton";
			this.resetButton.UseUnderline = true;
			this.resetButton.Label = global::Mono.Unix.Catalog.GetString ("Reset passwords");
			global::Gtk.Image w10 = new global::Gtk.Image ();
			w10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-properties", global::Gtk.IconSize.Dnd);
			this.resetButton.Image = w10;
			this.hbox1.Add (this.resetButton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.resetButton]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			w12.Padding = ((uint)(9));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.msgLabel = new global::Gtk.Label ();
			this.msgLabel.Name = "msgLabel";
			this.hbox4.Add (this.msgLabel);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.msgLabel]));
			w13.Position = 0;
			w13.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w14.Position = 2;
			w14.Expand = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.resetButton.Clicked += new global::System.EventHandler (this.OnResetButtonClicked);
		}
	}
}
