
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class SearchGroupWidget
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Image image1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry searchEntry;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView userTreeview;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Button editButton;
		
		private global::Gtk.Button promoteButton;
		
		private global::Gtk.Button demoteUsersButton;
		
		private global::Gtk.Button deleteGroupsButton;
		
		private global::Gtk.Button deleteUsersButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.SearchGroupWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.SearchGroupWidget";
			// Container child llum.SearchGroupWidget.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(6));
			this.GtkAlignment.TopPadding = ((uint)(6));
			this.GtkAlignment.RightPadding = ((uint)(6));
			this.GtkAlignment.BottomPadding = ((uint)(6));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Dialog);
			this.hbox3.Add (this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Search Group");
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Search filter:");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.searchEntry = new global::Gtk.Entry ();
			this.searchEntry.CanFocus = true;
			this.searchEntry.Name = "searchEntry";
			this.searchEntry.IsEditable = true;
			this.searchEntry.InvisibleChar = '●';
			this.hbox1.Add (this.searchEntry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.searchEntry]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.userTreeview = new global::Gtk.TreeView ();
			this.userTreeview.CanFocus = true;
			this.userTreeview.Name = "userTreeview";
			this.GtkScrolledWindow.Add (this.userTreeview);
			this.hbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
			w8.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.editButton = new global::Gtk.Button ();
			this.editButton.Sensitive = false;
			this.editButton.CanFocus = true;
			this.editButton.Name = "editButton";
			this.editButton.UseUnderline = true;
			this.editButton.Label = global::Mono.Unix.Catalog.GetString ("Edit Group");
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.editButton.Image = w9;
			this.vbox2.Add (this.editButton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.editButton]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.promoteButton = new global::Gtk.Button ();
			this.promoteButton.Sensitive = false;
			this.promoteButton.CanFocus = true;
			this.promoteButton.Name = "promoteButton";
			this.promoteButton.UseUnderline = true;
			this.promoteButton.Label = global::Mono.Unix.Catalog.GetString ("Promote Users from Group/s");
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			this.promoteButton.Image = w11;
			this.vbox2.Add (this.promoteButton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.promoteButton]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.demoteUsersButton = new global::Gtk.Button ();
			this.demoteUsersButton.Sensitive = false;
			this.demoteUsersButton.CanFocus = true;
			this.demoteUsersButton.Name = "demoteUsersButton";
			this.demoteUsersButton.UseUnderline = true;
			this.demoteUsersButton.Label = global::Mono.Unix.Catalog.GetString ("Demote Users from Group/s");
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
			this.demoteUsersButton.Image = w13;
			this.vbox2.Add (this.demoteUsersButton);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.demoteUsersButton]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.deleteGroupsButton = new global::Gtk.Button ();
			this.deleteGroupsButton.Sensitive = false;
			this.deleteGroupsButton.CanFocus = true;
			this.deleteGroupsButton.Name = "deleteGroupsButton";
			this.deleteGroupsButton.UseUnderline = true;
			this.deleteGroupsButton.Label = global::Mono.Unix.Catalog.GetString ("Delete Group/s");
			global::Gtk.Image w15 = new global::Gtk.Image ();
			w15.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.deleteGroupsButton.Image = w15;
			this.vbox2.Add (this.deleteGroupsButton);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.deleteGroupsButton]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.deleteUsersButton = new global::Gtk.Button ();
			this.deleteUsersButton.Sensitive = false;
			this.deleteUsersButton.CanFocus = true;
			this.deleteUsersButton.Name = "deleteUsersButton";
			this.deleteUsersButton.UseUnderline = true;
			this.deleteUsersButton.Label = global::Mono.Unix.Catalog.GetString ("Delete Users from Group/s");
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.deleteUsersButton.Image = w17;
			this.vbox2.Add (this.deleteUsersButton);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.deleteUsersButton]));
			w18.Position = 4;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w20.Position = 2;
			this.GtkAlignment.Add (this.vbox1);
			this.frame1.Add (this.GtkAlignment);
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.searchEntry.Changed += new global::System.EventHandler (this.OnSearchEntryChanged);
			this.userTreeview.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnUserTreeviewButtonReleaseEvent);
			this.editButton.Clicked += new global::System.EventHandler (this.OnEditButtonClicked);
			this.promoteButton.Clicked += new global::System.EventHandler (this.OnPromoteButtonClicked);
			this.demoteUsersButton.Clicked += new global::System.EventHandler (this.OnDemoteUsersButtonClicked);
			this.deleteGroupsButton.Clicked += new global::System.EventHandler (this.OnDeleteGroupsButtonClicked);
			this.deleteUsersButton.Clicked += new global::System.EventHandler (this.OnDeleteUsersButtonClicked);
		}
	}
}
