
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class FreezeWidget
	{
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image image230;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Image searchImage;
		
		private global::Gtk.Frame frame4;
		
		private global::Gtk.Alignment GtkAlignment6;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.TreeView availableGroupsTreeview;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Button freezeGroupButton;
		
		private global::Gtk.Image image247;
		
		private global::Gtk.Button unfreezeGroupButton;
		
		private global::Gtk.Image image248;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		
		private global::Gtk.TreeView frozenGroupsTreeview;
		
		private global::Gtk.Label GtkLabel6;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Frame frame5;
		
		private global::Gtk.Alignment GtkAlignment7;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		
		private global::Gtk.TreeView availableUsersTreeview;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.Button freezeUserButton;
		
		private global::Gtk.Image image249;
		
		private global::Gtk.Button unfreezeUserButton;
		
		private global::Gtk.Image image250;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow5;
		
		private global::Gtk.TreeView frozenUsersTreeview;
		
		private global::Gtk.Label GtkLabel7;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.Label msgLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.FreezeWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.FreezeWidget";
			// Container child llum.FreezeWidget.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(6));
			this.GtkAlignment.TopPadding = ((uint)(6));
			this.GtkAlignment.RightPadding = ((uint)(6));
			this.GtkAlignment.BottomPadding = ((uint)(6));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image230 = new global::Gtk.Image ();
			this.image230.Name = "image230";
			this.image230.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "frostwire", global::Gtk.IconSize.Dialog);
			this.hbox1.Add (this.image230);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image230]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Freeze Manager");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.searchImage = new global::Gtk.Image ();
			this.searchImage.Name = "searchImage";
			this.searchImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("llum.watch.gif");
			this.hbox1.Add (this.searchImage);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.searchImage]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(6));
			this.GtkAlignment6.TopPadding = ((uint)(6));
			this.GtkAlignment6.RightPadding = ((uint)(6));
			this.GtkAlignment6.BottomPadding = ((uint)(6));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.availableGroupsTreeview = new global::Gtk.TreeView ();
			this.availableGroupsTreeview.CanFocus = true;
			this.availableGroupsTreeview.Name = "availableGroupsTreeview";
			this.GtkScrolledWindow2.Add (this.availableGroupsTreeview);
			this.hbox10.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.GtkScrolledWindow2]));
			w6.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.freezeGroupButton = new global::Gtk.Button ();
			this.freezeGroupButton.CanFocus = true;
			this.freezeGroupButton.Name = "freezeGroupButton";
			// Container child freezeGroupButton.Gtk.Container+ContainerChild
			this.image247 = new global::Gtk.Image ();
			this.image247.Name = "image247";
			this.image247.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.freezeGroupButton.Add (this.image247);
			this.vbox7.Add (this.freezeGroupButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.freezeGroupButton]));
			w8.Position = 0;
			w8.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.unfreezeGroupButton = new global::Gtk.Button ();
			this.unfreezeGroupButton.CanFocus = true;
			this.unfreezeGroupButton.Name = "unfreezeGroupButton";
			// Container child unfreezeGroupButton.Gtk.Container+ContainerChild
			this.image248 = new global::Gtk.Image ();
			this.image248.Name = "image248";
			this.image248.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			this.unfreezeGroupButton.Add (this.image248);
			this.vbox7.Add (this.unfreezeGroupButton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.unfreezeGroupButton]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 1;
			w10.Fill = false;
			this.hbox10.Add (this.vbox7);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.vbox7]));
			w11.Position = 1;
			w11.Expand = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.frozenGroupsTreeview = new global::Gtk.TreeView ();
			this.frozenGroupsTreeview.CanFocus = true;
			this.frozenGroupsTreeview.Name = "frozenGroupsTreeview";
			this.GtkScrolledWindow3.Add (this.frozenGroupsTreeview);
			this.hbox10.Add (this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.GtkScrolledWindow3]));
			w13.Position = 2;
			this.vbox6.Add (this.hbox10);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox10]));
			w14.Position = 0;
			this.GtkAlignment6.Add (this.vbox6);
			this.frame4.Add (this.GtkAlignment6);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.Xpad = 6;
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Edit Groups</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel6;
			this.vbox1.Add (this.frame4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame4]));
			w17.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			w18.Padding = ((uint)(5));
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment7.Name = "GtkAlignment7";
			this.GtkAlignment7.LeftPadding = ((uint)(6));
			this.GtkAlignment7.TopPadding = ((uint)(6));
			this.GtkAlignment7.RightPadding = ((uint)(6));
			this.GtkAlignment7.BottomPadding = ((uint)(6));
			// Container child GtkAlignment7.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.availableUsersTreeview = new global::Gtk.TreeView ();
			this.availableUsersTreeview.CanFocus = true;
			this.availableUsersTreeview.Name = "availableUsersTreeview";
			this.GtkScrolledWindow4.Add (this.availableUsersTreeview);
			this.hbox11.Add (this.GtkScrolledWindow4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.GtkScrolledWindow4]));
			w20.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.freezeUserButton = new global::Gtk.Button ();
			this.freezeUserButton.CanFocus = true;
			this.freezeUserButton.Name = "freezeUserButton";
			// Container child freezeUserButton.Gtk.Container+ContainerChild
			this.image249 = new global::Gtk.Image ();
			this.image249.Name = "image249";
			this.image249.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.freezeUserButton.Add (this.image249);
			this.vbox9.Add (this.freezeUserButton);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.freezeUserButton]));
			w22.Position = 0;
			w22.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.unfreezeUserButton = new global::Gtk.Button ();
			this.unfreezeUserButton.CanFocus = true;
			this.unfreezeUserButton.Name = "unfreezeUserButton";
			// Container child unfreezeUserButton.Gtk.Container+ContainerChild
			this.image250 = new global::Gtk.Image ();
			this.image250.Name = "image250";
			this.image250.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			this.unfreezeUserButton.Add (this.image250);
			this.vbox9.Add (this.unfreezeUserButton);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.unfreezeUserButton]));
			w24.PackType = ((global::Gtk.PackType)(1));
			w24.Position = 1;
			w24.Fill = false;
			this.hbox11.Add (this.vbox9);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.vbox9]));
			w25.Position = 1;
			w25.Expand = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.frozenUsersTreeview = new global::Gtk.TreeView ();
			this.frozenUsersTreeview.CanFocus = true;
			this.frozenUsersTreeview.Name = "frozenUsersTreeview";
			this.GtkScrolledWindow5.Add (this.frozenUsersTreeview);
			this.hbox11.Add (this.GtkScrolledWindow5);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.GtkScrolledWindow5]));
			w27.Position = 2;
			this.vbox8.Add (this.hbox11);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox11]));
			w28.Position = 0;
			this.GtkAlignment7.Add (this.vbox8);
			this.frame5.Add (this.GtkAlignment7);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.Xpad = 6;
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Edit Users</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel7;
			this.vbox1.Add (this.frame5);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame5]));
			w31.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w32 = new global::Gtk.Viewport ();
			w32.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.msgLabel = new global::Gtk.Label ();
			this.msgLabel.Name = "msgLabel";
			w32.Add (this.msgLabel);
			this.scrolledwindow1.Add (w32);
			this.vbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow1]));
			w35.Position = 4;
			w35.Expand = false;
			this.GtkAlignment.Add (this.vbox1);
			this.Add (this.GtkAlignment);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.freezeGroupButton.Clicked += new global::System.EventHandler (this.OnFreezeGroupButtonClicked);
			this.unfreezeGroupButton.Clicked += new global::System.EventHandler (this.OnUnfreezeGroupButtonClicked);
			this.freezeUserButton.Clicked += new global::System.EventHandler (this.OnFreezeUserButtonClicked);
			this.unfreezeUserButton.Clicked += new global::System.EventHandler (this.OnUnfreezeUserButtonClicked);
		}
	}
}
