
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class LoginWidget
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Image image1;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry userEntry;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry passwordEntry;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ComboBox serverListcombobox;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Button connectButton;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.Label label4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.LoginWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.LoginWidget";
			// Container child llum.LoginWidget.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(8));
			// Container child vbox3.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("llum.llum.svg");
			this.vbox3.Add (this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(40));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("User");
			this.hbox2.Add (this.label5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label5]));
			w3.Position = 0;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.userEntry = new global::Gtk.Entry ();
			this.userEntry.CanFocus = true;
			this.userEntry.Name = "userEntry";
			this.userEntry.IsEditable = true;
			this.userEntry.InvisibleChar = '●';
			this.hbox2.Add (this.userEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.userEntry]));
			w4.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w5.Position = 2;
			w5.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.hbox3.Add (this.label6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label6]));
			w6.Position = 0;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.passwordEntry = new global::Gtk.Entry ();
			this.passwordEntry.CanFocus = true;
			this.passwordEntry.Name = "passwordEntry";
			this.passwordEntry.IsEditable = true;
			this.passwordEntry.Visibility = false;
			this.passwordEntry.InvisibleChar = '●';
			this.hbox3.Add (this.passwordEntry);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.passwordEntry]));
			w7.Position = 1;
			w7.Expand = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w8.Position = 3;
			w8.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 100;
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Connect to");
			this.hbox5.Add (this.label3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label3]));
			w9.Position = 0;
			w9.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.serverListcombobox = global::Gtk.ComboBox.NewText ();
			this.serverListcombobox.Name = "serverListcombobox";
			this.hbox5.Add (this.serverListcombobox);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.serverListcombobox]));
			w10.Position = 1;
			w10.Expand = false;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.connectButton = new global::Gtk.Button ();
			this.connectButton.CanFocus = true;
			this.connectButton.Name = "connectButton";
			this.connectButton.UseStock = true;
			this.connectButton.UseUnderline = true;
			this.connectButton.Label = "gtk-connect";
			this.hbox4.Add (this.connectButton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.connectButton]));
			w12.Position = 0;
			w12.Fill = false;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w13.Position = 5;
			w13.Expand = false;
			w13.Padding = ((uint)(10));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox3.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator2]));
			w14.Position = 6;
			w14.Expand = false;
			w14.Fill = false;
			w14.Padding = ((uint)(27));
			// Container child vbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter your user and password");
			this.vbox3.Add (this.label4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label4]));
			w15.Position = 7;
			w15.Expand = false;
			w15.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.hbox5.Hide ();
			this.Hide ();
			this.passwordEntry.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnPasswordEntryKeyPressEvent);
			this.connectButton.Clicked += new global::System.EventHandler (this.OnConnectButtonClicked);
		}
	}
}
