
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class AddUser
	{
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image image11;
		
		private global::Gtk.Image image12;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry nameEntry;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry surnameEntry;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry uidEntry;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.ComboBox templateCombobox;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.ComboBox groupCombobox;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry passwordEntry;
		
		private global::Gtk.HBox niaHbox;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry niaEntry;
		
		private global::Gtk.HBox dniHbox;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry dniEntry;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Button acceptButton;
		
		private global::Gtk.Button undoButton;
		
		private global::Gtk.Label msgLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.AddUser
			global::Stetic.BinContainer.Attach (this);
			this.Name = "llum.AddUser";
			// Container child llum.AddUser.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(6));
			this.GtkAlignment.TopPadding = ((uint)(6));
			this.GtkAlignment.RightPadding = ((uint)(6));
			this.GtkAlignment.BottomPadding = ((uint)(6));
			this.GtkAlignment.BorderWidth = ((uint)(6));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image11 = new global::Gtk.Image ();
			this.image11.Name = "image11";
			this.image11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_person", global::Gtk.IconSize.Dialog);
			this.hbox1.Add (this.image11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image12 = new global::Gtk.Image ();
			this.image12.Name = "image12";
			this.image12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.hbox1.Add (this.image12);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image12]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Add user");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 100;
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.nameEntry = new global::Gtk.Entry ();
			this.nameEntry.CanFocus = true;
			this.nameEntry.Name = "nameEntry";
			this.nameEntry.IsEditable = true;
			this.nameEntry.InvisibleChar = '●';
			this.hbox2.Add (this.nameEntry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.nameEntry]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 100;
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Surname");
			this.hbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.surnameEntry = new global::Gtk.Entry ();
			this.surnameEntry.CanFocus = true;
			this.surnameEntry.Name = "surnameEntry";
			this.surnameEntry.IsEditable = true;
			this.surnameEntry.InvisibleChar = '●';
			this.hbox3.Add (this.surnameEntry);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.surnameEntry]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 100;
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("User ID");
			this.hbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.uidEntry = new global::Gtk.Entry ();
			this.uidEntry.CanFocus = true;
			this.uidEntry.Name = "uidEntry";
			this.uidEntry.IsEditable = true;
			this.uidEntry.InvisibleChar = '●';
			this.hbox4.Add (this.uidEntry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.uidEntry]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.WidthRequest = 100;
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Template");
			this.hbox7.Add (this.label6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label6]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.templateCombobox = global::Gtk.ComboBox.NewText ();
			this.templateCombobox.Name = "templateCombobox";
			this.hbox7.Add (this.templateCombobox);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.templateCombobox]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add (this.hbox7);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.WidthRequest = 100;
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Group");
			this.hbox8.Add (this.label10);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label10]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.groupCombobox = global::Gtk.ComboBox.NewText ();
			this.groupCombobox.Name = "groupCombobox";
			this.hbox8.Add (this.groupCombobox);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.groupCombobox]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox1.Add (this.hbox8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
			w19.Position = 5;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.WidthRequest = 100;
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.hbox6.Add (this.label5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label5]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.passwordEntry = new global::Gtk.Entry ();
			this.passwordEntry.CanFocus = true;
			this.passwordEntry.Name = "passwordEntry";
			this.passwordEntry.IsEditable = true;
			this.passwordEntry.InvisibleChar = '●';
			this.hbox6.Add (this.passwordEntry);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.passwordEntry]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w22.Position = 6;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.niaHbox = new global::Gtk.HBox ();
			this.niaHbox.Name = "niaHbox";
			this.niaHbox.Spacing = 6;
			// Container child niaHbox.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.WidthRequest = 100;
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("NIA");
			this.niaHbox.Add (this.label7);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.niaHbox [this.label7]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child niaHbox.Gtk.Box+BoxChild
			this.niaEntry = new global::Gtk.Entry ();
			this.niaEntry.CanFocus = true;
			this.niaEntry.Name = "niaEntry";
			this.niaEntry.IsEditable = true;
			this.niaEntry.InvisibleChar = '●';
			this.niaHbox.Add (this.niaEntry);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.niaHbox [this.niaEntry]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox1.Add (this.niaHbox);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.niaHbox]));
			w25.Position = 7;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.dniHbox = new global::Gtk.HBox ();
			this.dniHbox.Name = "dniHbox";
			this.dniHbox.Spacing = 6;
			// Container child dniHbox.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.WidthRequest = 100;
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("DNI");
			this.dniHbox.Add (this.label9);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.dniHbox [this.label9]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child dniHbox.Gtk.Box+BoxChild
			this.dniEntry = new global::Gtk.Entry ();
			this.dniEntry.CanFocus = true;
			this.dniEntry.Name = "dniEntry";
			this.dniEntry.IsEditable = true;
			this.dniEntry.InvisibleChar = '●';
			this.dniHbox.Add (this.dniEntry);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.dniHbox [this.dniEntry]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox1.Add (this.dniHbox);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.dniHbox]));
			w28.Position = 8;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator2]));
			w29.Position = 9;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("* NIA/DNI fields are optional, but if present, they will help the re-importation process");
			this.label8.Wrap = true;
			this.vbox1.Add (this.label8);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label8]));
			w30.Position = 10;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w31.Position = 11;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 60;
			this.hbox5.BorderWidth = ((uint)(6));
			// Container child hbox5.Gtk.Box+BoxChild
			this.acceptButton = new global::Gtk.Button ();
			this.acceptButton.CanFocus = true;
			this.acceptButton.Name = "acceptButton";
			this.acceptButton.UseStock = true;
			this.acceptButton.UseUnderline = true;
			this.acceptButton.Label = "gtk-ok";
			this.hbox5.Add (this.acceptButton);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.acceptButton]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.undoButton = new global::Gtk.Button ();
			this.undoButton.CanFocus = true;
			this.undoButton.Name = "undoButton";
			this.undoButton.UseStock = true;
			this.undoButton.UseUnderline = true;
			this.undoButton.Label = "gtk-undo";
			this.hbox5.Add (this.undoButton);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.undoButton]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w34.Position = 12;
			w34.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.msgLabel = new global::Gtk.Label ();
			this.msgLabel.Name = "msgLabel";
			this.vbox1.Add (this.msgLabel);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.msgLabel]));
			w35.PackType = ((global::Gtk.PackType)(1));
			w35.Position = 13;
			w35.Expand = false;
			w35.Fill = false;
			this.GtkAlignment.Add (this.vbox1);
			this.frame1.Add (this.GtkAlignment);
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.nameEntry.Changed += new global::System.EventHandler (this.OnNameEntryChanged);
			this.surnameEntry.Changed += new global::System.EventHandler (this.OnSurnameEntryChanged);
			this.uidEntry.Changed += new global::System.EventHandler (this.OnUidEntryChanged);
			this.templateCombobox.Changed += new global::System.EventHandler (this.OnTemplateComboboxChanged);
			this.passwordEntry.Changed += new global::System.EventHandler (this.OnPasswordEntryChanged);
			this.niaEntry.Changed += new global::System.EventHandler (this.OnPasswordEntryChanged);
			this.dniEntry.Changed += new global::System.EventHandler (this.OnPasswordEntryChanged);
			this.acceptButton.Clicked += new global::System.EventHandler (this.OnAcceptButtonClicked);
			this.undoButton.Clicked += new global::System.EventHandler (this.OnUndoButtonClicked);
		}
	}
}
