
// This file has been generated by the GUI designer. Do not modify.
namespace llum
{
	public partial class ProgressWindow
	{
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.ProgressBar progressbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget llum.ProgressWindow
			this.Name = "llum.ProgressWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ProgressWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			// Container child llum.ProgressWindow.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.Name = "progressbar1";
			this.vbox6.Add (this.progressbar1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.progressbar1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 353;
			this.DefaultHeight = 52;
			this.Show ();
		}
	}
}
