
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox mainHBox;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.VBox buttonVbox;
	
	private global::Gtk.Button exitButton;
	
	private global::Gtk.VSeparator vseparator1;
	
	private global::Gtk.VBox widgetVbox;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Image world_image;
	
	private global::Gtk.Label statusLabel;
	
	private global::Gtk.Button disconnectButton;
	
	private global::Gtk.HSeparator hseparator3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Llum - Lliurex User Manager");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_3d-light-on", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainHBox = new global::Gtk.HBox ();
		this.mainHBox.Name = "mainHBox";
		this.mainHBox.Spacing = 6;
		this.mainHBox.BorderWidth = ((uint)(6));
		// Container child mainHBox.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 220;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
		w1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.buttonVbox = new global::Gtk.VBox ();
		this.buttonVbox.WidthRequest = 160;
		this.buttonVbox.Name = "buttonVbox";
		this.buttonVbox.Spacing = 6;
		this.buttonVbox.BorderWidth = ((uint)(4));
		w1.Add (this.buttonVbox);
		this.GtkScrolledWindow.Add (w1);
		this.vbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
		w4.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.exitButton = new global::Gtk.Button ();
		this.exitButton.CanFocus = true;
		this.exitButton.Name = "exitButton";
		this.exitButton.UseStock = true;
		this.exitButton.UseUnderline = true;
		this.exitButton.Label = "gtk-quit";
		this.vbox3.Add (this.exitButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.exitButton]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.mainHBox.Add (this.vbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.mainHBox [this.vbox3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child mainHBox.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.Name = "vseparator1";
		this.mainHBox.Add (this.vseparator1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.mainHBox [this.vseparator1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child mainHBox.Gtk.Box+BoxChild
		this.widgetVbox = new global::Gtk.VBox ();
		this.widgetVbox.Name = "widgetVbox";
		this.widgetVbox.Spacing = 6;
		// Container child widgetVbox.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.world_image = new global::Gtk.Image ();
		this.world_image.Name = "world_image";
		this.world_image.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_internet", global::Gtk.IconSize.Menu);
		this.hbox5.Add (this.world_image);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.world_image]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.statusLabel = new global::Gtk.Label ();
		this.statusLabel.Name = "statusLabel";
		this.hbox5.Add (this.statusLabel);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.statusLabel]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.disconnectButton = new global::Gtk.Button ();
		this.disconnectButton.Sensitive = false;
		this.disconnectButton.CanFocus = true;
		this.disconnectButton.Name = "disconnectButton";
		this.disconnectButton.UseStock = true;
		this.disconnectButton.UseUnderline = true;
		this.disconnectButton.Label = "gtk-disconnect";
		this.hbox5.Add (this.disconnectButton);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.disconnectButton]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.widgetVbox.Add (this.hbox5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.widgetVbox [this.hbox5]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child widgetVbox.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.widgetVbox.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.widgetVbox [this.hseparator3]));
		w12.PackType = ((global::Gtk.PackType)(1));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.mainHBox.Add (this.widgetVbox);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.mainHBox [this.widgetVbox]));
		w13.Position = 2;
		this.Add (this.mainHBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 698;
		this.DefaultHeight = 492;
		this.world_image.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.exitButton.Clicked += new global::System.EventHandler (this.OnExitButtonClicked);
		this.disconnectButton.Clicked += new global::System.EventHandler (this.OnDisconnectButtonClicked);
	}
}
