#!/usr/bin/env python
# -*- coding: utf-8 -*-
 
 
import sys
import os 
if __name__ == '__main__':
    if len(sys.argv) > 1:
        url = sys.argv[1]
    else:
        url = "http://lliurex.net"
    
    os.system("xdg-open %s"%url)
    sys.exit(9)
